### ISSUE TITLE
Enhancement: convert cond to case in types.clj

### ISSUE THREAD

**Issue by oubiwann** [clojusc/mesomatic#18]
There's one `cond` left in `mesomatic.types` that is able to be converted to a case.

This makes the code more readable, and brings the `data->pb` function in line with the other functions in the namespace that are amenable to using `case` (the ones that aren't checking against Java fields).

The work for this was done in this branch:
- https://github.com/clojusc/mesomatic/commits/cond-to-case

**Comment by alexandergunnarson** [comment]
I was able to transform quite a few more `cond`s to `case`s than just the last one in `mesomatic.types`. If it's checking against any compile-type constant (keywords included, not just numbers or Java enums), then `case` is valid and wins over `cond` in terms of performance and readability. You can take a look at the PR [here](https://github.com/pyr/mesomatic/pull/21).

**Comment by oubiwann** [comment]
@alexandergunnarson Nice! I was on vacation, so didn't see this until just now. I've merged your changes into the branch I worked on (https://github.com/clojusc/mesomatic/pull/1), and I've also merged these changes into the "deploy" branch we're using at USGS (https://github.com/clojusc/mesomatic/tree/deploy).

Thanks!

**Comment by alexandergunnarson** [comment]
@oubiwann No problem! Thanks for merging it.

**Comment by oubiwann** [comment]
Closing this ticket since @alexandergunnarson's newer branch supersedes it.
