### ISSUE TITLE
Plan to switch to HTTP api?

### ISSUE THREAD

**Issue by wyegelwel** [clojusc/mesomatic#22]
I was wondering if there was any plan to switch mesomatic to use the new HTTP api since the java lib is being deprecated.

**Comment by oubiwann** [comment]
I've been working on an implementation of this here:
- https://github.com/oubiwann/meson

I've committed the `types.clj` namespace from Mesomatic to Meson (as @pyr) but have started refactoring for use by more than just the mesos protobuf definition (the scheduler, executor, and operator APIs each define their own protobufs and we need types for those as well).

Anyway, it's very early days for that project, but I'm working on it as I get the time. I've got milestones defined, with tickets in each, here:
- https://github.com/oubiwann/meson/milestones

Current development is happening here:
- https://github.com/oubiwann/meson/milestone/2

(Note that the failing test right now is the user agent string -- different java version on Travis than local.)

**Comment by pyr** [comment]
Hi @wyegelwel, I think it would be worthwhile, if only for the standardized logging. I have an asynchronous TCP & HTTP library which would be a good basis for it. I would say though that you shouldn't hold your breath as my work on mesomatic is slow-paced.
