### ISSUE TITLE
Args for 5-arity MesomaticSchedulerDriver init in wrong order

### ISSUE THREAD

**Issue by oubiwann** [clojusc/mesomatic#34]
Java code:

``` java
public MesosSchedulerDriver(Scheduler scheduler,
                            FrameworkInfo framework,
                            String master,
                            boolean implicitAcknowledgements,
                            Credential credential) { ... }
```

Mesomatic code:

``` clj
(MesosSchedulerDriver. scheduler
  (->pb :FrameworkInfo framework)
  master
  (->pb :Credential credential)
  implicit-acknowledgements?))))
```

Totally my fault -- I'll submit a fix and PR...

**Comment by pyr** [comment]
fixed now, thanks @oubiwann

**Comment by pyr** [comment]
By the way, we have stopped using mesomatic internally and I'm willing to hand it over if you will.

**Comment by oubiwann** [comment]
Thanks for the recent merges!

And sad to hear that you're not using Mesos anymore :-( That being said, your contributions to the Mesos world have been greatly appreciated!

Would love to maintain mesomatic -- I've added you to a Clojure org I manage, giving you elevated perms (last I checked, this was needed in order to do project transfers). If this is what you had in mind, I'll update the README after transfer, with a note about the project now being maintained in the clojusc org. Github manages forwarding, too -- the old URL will point to wherever you transfer the project (but I'm sure you already know this!).

**Comment by pyr** [comment]
hey, yes that's perfect. there's already a mesomatic fork in the clojusc org so the transfer can't go ahead. I'll let you handle that and will reattempt transfer. Cheers!

**Comment by oubiwann** [comment]
Just renamed the fork -- should be good to go, now -- thanks!

**Comment by pyr** [comment]
It seems to be insufficient, I'm now seeing the following message:

> clojusc already has a repository in the pyr/mesomatic network

**Comment by oubiwann** [comment]
Ugh, if I'd my wits about me, I'd have moved it to another org instead of renaming. That's fixed now -- no fork for mesomatic is in the clojusc org anymore.

Sorry for the hassle!

**Comment by pyr** [comment]
it's now done, thanks again!

**Comment by oubiwann** [comment]
Fantastic :-)

Glad I could help!
