### ISSUE TITLE
"Asked to abort the driver"

### ISSUE THREAD

**Issue by wyegelwel** [clojusc/mesomatic#38]
I'm in a bit of a pickle and am hoping you can help. Periodically our scheduler disconnects from mesos and from the mesos logs on the scheduler side, I see:

```
I20161007 22:18:10.539175 28448 authenticatee.cpp:336] Authentication success
I20161007 22:18:10.539458 28455 sched.cpp:472] Successfully authenticated with master master@172.22.22.131:5050
I20161007 22:18:10.540596 28445 sched.cpp:708] Framework registered with 20150506-201345-1963923116-5050-3887-0002
I20161007 22:28:13.041359 28452 sched.cpp:1942] Asked to abort the driver
I20161007 22:28:13.041808 28452 sched.cpp:1178] Aborting framework '20150506-201345-1963923116-5050-3887-0002'
```

But I can't find any corresponding error that would imply why the driver is aborting. Have any of you seen something like this before? What steps can you recommend to debug? I've poured over both the scheduler and mesos master logs around the time to see if there was anything that jumped out but unfortunately not.

**Comment by wyegelwel** [comment]
Ok, I think I figured it out. I'm an idiot. My apologizes for this issue. I created a repro by having an exception be thrown in the TaskStatus `pb->data` function which nicely exhibited the problem. Then I realized the exception had to be going somewhere and sure enough it was in the log that I _thought_ I had emptied reference to. It has been a long night. Have a great weekend!

**Comment by pyr** [comment]
no worries, glad things worked out :-)
