### ISSUE TITLE
Support for Mesos >= 1.3.0?

### ISSUE THREAD

**Issue by m4ce** [clojusc/mesomatic#39]
Mesomatic depends on Mesos 1.0.1. Are there any plans to update it to support more recent versions of Mesos?

**Comment by pyr** [comment]
I'm looking for a new maintainer for the project as we have sunsetted our usage of mesomatic.

**Comment by oubiwann** [comment]
Hey @m4ce, there are definitely plans to support subsequent releases of Mesos. 

Steps are roughly the following:
* Decide upon a system / integration test strategy
* Create some basic integration tests, targeted initially at just the changes between versions (see  http://mesos.apache.org/documentation/latest/upgrades/)
* Step through the version changes from 1.0.1 up through the latest release (1.4.1 as of now), adding tests to ensure Mesomatic continues to work as expected

There are very few changes to the Java API, so this should be a fairly straight-forward process, once a Travis-CI-friendly testing strategy has been decided upon.

**Comment by oubiwann** [comment]
I've created an epic for this: #43

I'm going to close this ticket as answered ...
